<?php
function loadDotEnv($path) {
    if (!is_file($path) || !is_readable($path)) {
        return;
    }

    $lines = file($path, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);

    foreach ($lines as $line) {
        $trimmed = trim($line);

        if ($trimmed === '' || str_starts_with($trimmed, '#') || !str_contains($trimmed, '=')) {
            continue;
        }

        [$name, $value] = explode('=', $trimmed, 2);
        $name = trim($name);
        $value = trim($value);

        if ($name === '' || getenv($name) !== false) {
            continue;
        }

        if (
            (str_starts_with($value, '"') && str_ends_with($value, '"')) ||
            (str_starts_with($value, "'") && str_ends_with($value, "'"))
        ) {
            $value = substr($value, 1, -1);
        }

        putenv($name . '=' . $value);
        $_ENV[$name] = $value;
        $_SERVER[$name] = $value;
    }
}

loadDotEnv(__DIR__ . DIRECTORY_SEPARATOR . '.env');

function envValue($key, $default = null) {
    $value = getenv($key);
    return $value === false || $value === '' ? $default : $value;
}

function buildDatabaseConfig() {
    $databaseUrl = envValue('DATABASE_URL');

    if ($databaseUrl) {
        $parts = parse_url($databaseUrl);

        if ($parts === false) {
            die('Invalid DATABASE_URL value.');
        }

        parse_str($parts['query'] ?? '', $queryParams);

        return [
            'host' => $parts['host'] ?? '127.0.0.1',
            'port' => isset($parts['port']) ? (int) $parts['port'] : 5432,
            'dbname' => isset($parts['path']) ? rawurldecode(ltrim($parts['path'], '/')) : 'image_gallery',
            'user' => isset($parts['user']) ? rawurldecode($parts['user']) : '',
            'pass' => isset($parts['pass']) ? rawurldecode($parts['pass']) : '',
            'sslmode' => $queryParams['sslmode'] ?? null,
        ];
    }

    return [
        'host' => envValue('DB_HOST', '127.0.0.1'),
        'port' => (int) envValue('DB_PORT', '5432'),
        'dbname' => envValue('DB_NAME', 'image_gallery'),
        'user' => envValue('DB_USER', 'postgres'),
        'pass' => envValue('DB_PASS', ''),
        'sslmode' => envValue('DB_SSLMODE'),
    ];
}

function storageRoot() {
    static $root = null;

    if ($root === null) {
        $configured = envValue('STORAGE_ROOT', __DIR__);
        $root = rtrim($configured, '/\\');
    }

    return $root;
}

function storageUrlRoot() {
    static $urlRoot = null;

    if ($urlRoot === null) {
        $configured = envValue('STORAGE_URL_ROOT');

        if ($configured !== null && $configured !== '') {
            $urlRoot = trim($configured, '/');
            return $urlRoot;
        }

        $root = str_replace('\\', '/', storageRoot());
        $appRoot = str_replace('\\', '/', __DIR__);

        if ($root === $appRoot) {
            $urlRoot = '';
        } elseif ($root === $appRoot . '/storage') {
            $urlRoot = 'storage';
        } else {
            $urlRoot = '';
        }
    }

    return $urlRoot;
}

function storagePath($directory, $filename = '') {
    $path = storageRoot() . DIRECTORY_SEPARATOR . trim($directory, '/\\');

    if ($filename !== '') {
        $path .= DIRECTORY_SEPARATOR . ltrim($filename, '/\\');
    }

    return $path;
}

function publicAssetPath($directory, $filename = '') {
    $parts = [];
    $urlRoot = storageUrlRoot();

    if ($urlRoot !== '') {
        $parts[] = $urlRoot;
    }

    $parts[] = trim($directory, '/');
    $path = implode('/', array_filter($parts, fn ($part) => $part !== ''));

    if ($filename !== '') {
        $path .= '/' . rawurlencode($filename);
    }

    return $path;
}

function ensureDirectory($path) {
    if (!is_dir($path) && !mkdir($path, 0777, true) && !is_dir($path)) {
        die("Failed to create directory: " . $path);
    }
}

$dbConfig = buildDatabaseConfig();

$dsn = sprintf(
    'pgsql:host=%s;port=%d;dbname=%s',
    $dbConfig['host'],
    $dbConfig['port'],
    $dbConfig['dbname']
);

if (!empty($dbConfig['sslmode'])) {
    $dsn .= ';sslmode=' . $dbConfig['sslmode'];
}

try {
    $conn = new PDO($dsn, $dbConfig['user'], $dbConfig['pass'], [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
        PDO::ATTR_EMULATE_PREPARES => false,
    ]);
} catch (PDOException $e) {
    die('Connection failed: ' . $e->getMessage());
}

$schemaSql = "CREATE TABLE IF NOT EXISTS images (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filename VARCHAR(255) NOT NULL,
    title VARCHAR(255),
    description TEXT,
    category VARCHAR(100),
    uploaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    views INTEGER NOT NULL DEFAULT 0
)";

try {
    $conn->exec($schemaSql);
} catch (PDOException $e) {
    die('Error creating table: ' . $e->getMessage());
}

ensureDirectory(storagePath('images'));
ensureDirectory(storagePath('thumbs'));
?>
