CREATE TABLE IF NOT EXISTS images (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  filename VARCHAR(255) NOT NULL,
  title VARCHAR(255),
  description TEXT,
  category VARCHAR(100),
  uploaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  views INTEGER NOT NULL DEFAULT 0
);

INSERT INTO images (id, filename, title, description, category, uploaded_at, views) VALUES
(1, 'nature_1.jpg', 'Mountain Landscape', 'Beautiful mountain view at sunrise', 'Nature', '2025-12-18 06:28:48', 42),
(2, 'nature_2.webp', 'Forest Path', 'Peaceful forest walking path', 'Nature', '2025-12-18 06:28:48', 28),
(3, 'travel_1.jpg', 'Paris Eiffel Tower', 'Iconic Eiffel Tower in Paris', 'Travel', '2025-12-18 06:28:48', 56),
(4, 'travel_2.jpg', 'Tokyo Street', 'Busy street in Tokyo at night', 'Travel', '2025-12-18 06:28:48', 31),
(5, 'art_1.jpg', 'Abstract Painting', 'Colorful abstract art painting', 'Art', '2025-12-18 06:28:48', 19),
(6, 'food_1.jpg', 'Delicious Pizza', 'Homemade pepperoni pizza', 'Food', '2025-12-18 06:28:48', 67),
(7, 'food_2.jpeg', 'Fresh Salad', 'Healthy vegetable salad bowl', 'Food', '2025-12-18 06:28:48', 24),
(8, 'people_1.jpg', 'Portrait Photography', 'Professional portrait photo', 'People', '2025-12-18 06:28:48', 15),
(9, 'city_1.webp', 'New York Skyline', 'New York city skyline at dusk', 'City', '2025-12-18 06:28:48', 89),
(10, 'animals_1.jpg', 'Cute Puppy', 'Golden retriever puppy playing', 'Animals', '2025-12-18 06:28:48', 112)
ON CONFLICT (id) DO NOTHING;

SELECT setval(
  pg_get_serial_sequence('images', 'id'),
  COALESCE((SELECT MAX(id) FROM images), 1),
  true
);
